- name: "blocked"
  color: "f9d0c4"
  description: "This item cannot be completed yet"
- name: "defect"
  color: "d93f0b"
  description: "Something isn't working"
- name: "priority: one"
  color: "c2e0c6"
  description: "This item is essential to functionality"
- name: "priority: two"
  color: "c2e0c6"
  description: "This item would improve functionality"
- name: "needs attention"
  color: "d93f0b"
  description: "Further information is requested"
- name: "ui"
  color: "5319e7"
  description: "This item is related to the user interface"
- name: "ai"
  color: "5319e7"
  description: "This item is related to the artificial intelligence"
- name: "core"
  color: "5319e7"
  description: "This item is related to the game core"
- name: "networking"
  color: "5319e7"
  description: "This item is related to networking"