- name: "approved"
  color: "5319e7"
  description: "This item is ready to be worked on"
- name: "blocked"
  color: "f9d0c4"
  description: "This item cannot be completed yet"
- name: "defect"
  color: "d93f0b"
  description: "Something isn't working"
- name: "complete"
  color: "f9d0c4"
  description: "Development on this item is finished"
- name: "enhancement"
  color: "c5def5"
  description: "This item improves existing functionality"
- name: "in development"
  color: "c2e0c6"
  description: "This item is in development"
- name: "needs attention"
  color: "d93f0b"
  description: "Further information is requested"
- name: "new feature"
  color: "c5def5"
  description: "This item creates new functionality"